[package]
name = "chat-ws"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
aspeak = "6.0.1"
axum = { version = "0.6.20", features = ["ws", "headers"] }
crossbeam-channel = "0.5.8"
dotenv = "0.15.0"
flume = "0.11.0"
futures = "0.3.28"
futures-util = "0.3.28"
md-5 = "0.10.6"
openai_dive = "0.2.13"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
tokio = { version = "1.32.0", features = ["full"] }
tower-http = { version = "0.4.4", features = ["fs", "trace"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
uuid = "1.4.1"
